### ISSUE TITLE
Incorrect fragment for collection

### ISSUE THREAD

**Issue by faceless2** [w3c/woff2-tests#16]
The test `available-002.xht` generated by `UserAgentTestCaseGenerator.py` creates a WOFF2 collection with two fonts - or, more accurately, two copies of the same font, the second with a transform to make the font look condensed horizontally.

It then genererates two iframes to load each font from the collection:

```css
@font-face {
   font-family: "WOFF Test";
   src: url("available-002.woff2#1") format("woff2");
}
```
and
```css
@font-face {
   font-family: "WOFF Test";
   src: url("available-002.woff2#2") format("woff2");
}
```
There are a couple of problems with this.

First, there's nothing to support the idea that a numeric value for the fragment can be used to load a particular font; I recall this was a sort of de-facto approach in the early days, but it's not in https://datatracker.ietf.org/doc/html/rfc8081#page-5.

The RFC states that the fragment must be the font's PostScript name, which leads to the second problem: the two copies of the font both share the name table, so both have the same name.

According to https://github.com/w3c/csswg-drafts/issues/2566, as neither fragment matches a PostScript name they're both ignored and we end up with two copies of the first font in the collection - two copies of the uncondensed font. Which means the current the behaviour of Chrome for http://wpt.live/css/WOFF2/available-002.xht is correct.

The solution would be to give the second copy of the font a different name, and refer to the fonts by fragment, eg

```css
@font-face {
   font-family: "WOFF Test";
   src: url("available-002.woff2#WOFFTestTTF0-Regular") format("woff2");
}
```

but I don't know how to change the font name with the the fonttools API, so no pull request to fix this - sorry.
